server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gilgameshs/gilgamesh-config-repo.git
          basedir: target/config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: /admin/health
    status-page-url-path: /admin/info
    lease-renewal-interval-in-seconds: 10